### PR TITLE
add .pylintrc and pylint.sh, resolves #29

### LINKED ISSUE #29: continuous integration
Set up CI just like in gpkit.

GitHub is currently advertising a lot of CI integrations: https://github.com/integrations/feature/code. @galbramc, any thoughts on whether those are worth looking in to, or is another Jenkins setup our best bet?

### PR DESCRIPTION
**Pull request by whoburg**
@galbramc, could you give this a quick review please. Adding pylint items as described/requested in #29.

### CODE REVIEW

**Comment by galbramc** [comment]
Test this please

**Comment by galbramc** [comment]
Test this please

**Comment by galbramc** [comment]
Test this please

**Comment by galbramc** [comment]
Test this please

**Comment by galbramc** [comment]
Pylint is setup, but one of the tests still fails sporadically. I think you have an issue open for that all ready though. Go ahead and merge.

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
I realized we had different versions of pylint installed on the different computers. I just got them all upgraded to the same version, so the warnings should be more consistent across the different OSs

**Comment by whoburg** [comment]
Great, thanks!

**Pull request merged**
