### PR TITLE
change monomial equality creation for SMA, k=1

### PR DESCRIPTION
**Pull request by mjburton11**
@whoburg, @bqpd: ready for review: 

I've been getting the below error when trying to fit data with SMA, K=1.  I believe this PR will fix it.

```python 
/Users/mjburton11/anaconda/lib/python2.7/site-packages/gpfit/fit.pyc in fit(xdata, ydata, K, ftype, varNames)
    165         # # If only one term, automatically make an equality constraint
    166         if K == 1:
--> 167             cstrt = MonomialEquality(cstrt, "=", 1)
    168 
    169 

/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, left, oper, right)
    566     def __init__(self, left, oper, right):
    567         # pylint: disable=non-parent-init-called
--> 568         ScalarSingleEquationConstraint.__init__(self, left, oper, right)
    569         if self.oper is not "=":
    570             raise ValueError("operator %s is not supported by"

/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, left, oper, right)
    411     def __init__(self, left, oper, right):
    412         super(ScalarSingleEquationConstraint,
--> 413               self).__init__(Signomial(left), oper, Signomial(right))
    414         self.varkeys = KeySet(self.left.varlocs)
    415         self.varkeys.update(self.right.varlocs)

/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, exps, cs, require_positive, simplify, **descr)
     71             try:
     72                 # test for presence of length and identical lengths
---> 73                 assert len(cs) == len(exps)
     74                 exps_ = list(range(len(exps)))
     75                 if not all(isinstance(c, Quantity) for c in cs):

TypeError: object of type 'int' has no len()
```

### CODE REVIEW

**Comment by mjburton11** [comment]
Also got the same error when using ISMA for K=1.

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
All the tests are passing. Ignore anything other than "gpfit pylint tests" and "gpfit unit tests"

**Comment by bqpd** [comment]
@mjburton11, there seem to be pylint errors on this?

**Comment by galbramc** [comment]
are the changes to .pylintrc here consistent with those in gpkit?

**Comment by bqpd** [comment]
Not entirely, because Philippe favoured different variable names than I
did. I think unifying the two would make sense as an issue on this repo,
though.

**Comment by bqpd** [comment]
@galbramc, pylint consistency is now captured in issue #63

**Pull request merged**
