### PR TITLE
fix changing example output

### PR DESCRIPTION
**Pull request by whoburg**
by seeding

### CODE REVIEW

**Comment by whoburg** [comment]
@galbramc, I think this should resolve the changing output, however Jenkins is still failing because of how it is currently set up to run the examples.

Our unit tests run the examples automatically (just like in gpkit), via `t_examples`. The output files are generated when the unit tests are run. In this PR, that file now has a seeded random number generator so that the output will not change.

It looks to me like Jenkins tries to run the unit tests itself (search the script for `for i in '`ls $WORKSPACE/docs/source/examples/*.py`'`). This will create different output every time.

Can you please edit the script to let the unit tests create the output files, but still compare them? (like in GPkit)

**Comment by galbramc** [comment]
Hmmm, so part of the reason for running ```for i in 'ls $WORKSPACE/docs/source/examples/*.py``` is to make sure that all examples are executed even if someone forgot to include them in ```t_examples```. I can remove that part of the script if you want, but this is the exact same setup I have for gpkit.

**Comment by galbramc** [comment]
Actually, as a user, I think it would be a bit unsettling if I grabbed your code, ran the examples, and then got different answers than what the documentation says it should be. I my first reaction would probably be to assume that I did something wrong before I realized your example has a random number and hence produces different results every time you run it... Are you sure you don't want to put the seed in the example it self?

**Comment by whoburg** [comment]
ok good point, I've moved the seed to the example file

**Comment by whoburg** [comment]
grr, not sure I can account for the mismatch on Reynolds. Maybe the seeding process works differently there somehow?

**Comment by galbramc** [comment]
Actually, I think I've heard that the seeding only guarantees the same random number on a given machine. Any changes in compiler or OS will result in a different random seeded number... Can you hard code the random number?

**Comment by whoburg** [comment]
It's more than one random number, so that would be awkward.

**Comment by whoburg** [comment]
by the way, why was this passing before? we're suddenly red on the homepage...

**Comment by galbramc** [comment]
It was passing before because checking if the example output has changed was missing from the jenkins script. I added it to gpkit way back when, but I had not added it to gpfit.

Yeah I don't know what to do about unit testing with random number generators...  Maybe this 'mock' library is what you want?

http://stackoverflow.com/questions/22457371/python-injecting-random-number-into-tests

**Comment by whoburg** [comment]
ok I don't know how to fix this issue right now. @galbramc could you please disable that check for now, we were not ready to enable it on this repo.

**Comment by galbramc** [comment]
The checks have been turned off at your own peril. The status of the example output file will always show up as changed.

**Comment by galbramc** [comment]
test this please

**Comment by whoburg** [comment]
ok thanks! hope to fix this eventually; that's captured in #33.

**Pull request merged**
