### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by pgkirsch**
Creating a setup.py to facilitate installation of gpfit system-wide. Ready for a quick review @whoburg (or @bqpd).

### CODE REVIEW

**Comment by bqpd** [comment]
I like it! Give it a real version number, though? I think this deserves a 1.0...

**Comment by pgkirsch** [comment]
Oops I didn't realise it was 0.0. Given that the code still kind of sucks, and in keeping with the current GPkit precedent, I went with a 0.1 instead. Thanks for catching that!

**Comment by whoburg** [comment]
Thanks @pgkirsch!

**Comment by whoburg** [comment]
Is this an expected warning?
`/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'`

**Comment by whoburg** [comment]
@galbramc, we now have a setup script for gpfit -- should Jenkins be updated to use it?

**Comment by galbramc** [comment]
Yep, Jenkins should be using it so that the script it self gets tested. I'll make the updates.

**Comment by galbramc** [comment]
@whoburg and @pgkirsch, I updated the Jenkins scripts, but now Jenkins is failing because the example is producing different results than what is stored in the repo.

**Comment by whoburg** [comment]
see #52

**Pull request merged**
