### PR TITLE
update constraint class names for latest GPkit

### LINKED ISSUE #37: gpfit not updated to match gpkit
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Users/mjburton11/Documents/SuperUROP/gpkit-models/1682/gas_male/Datasets/fitDF70.py in <module>()
      2 
      3 import gpfit
----> 4 from gpfit.fit import fit
      5 import numpy as np
      6 import pandas as pd

/Users/mjburton11/Documents/SuperUROP/gpfit/gpfit/fit.py in <module>()
      6 from max_affine_init import max_affine_init
      7 from print_fit import print_ISMA, print_SMA, print_MA
----> 8 from gpkit.nomials import Posynomial, Monomial, Constraint, MonoEQConstraint
      9 from numpy import append, ones, exp, sqrt, mean, square
     10 

ImportError: cannot import name Constraint
```

### PR DESCRIPTION
**Pull request by whoburg**
fixes #37

### CODE REVIEW

**Comment by whoburg** [comment]
ready for review.

**Comment by whoburg** [comment]
@galbramc can you please reset the pylint counts. I fixed 26 warnings and the more I fix the more get incorrectly spawned as "new".

**Comment by galbramc** [comment]
yeah I can fix the counts, but we have to time this well. I think the best way to fix the counts is for you to merge this branch, and then we can reset the counts on both the gpkit_push and gpkit_pullrequest. I'm in crete and 7 hours ahead of you. Hopefully we can coordinate this evening for me and morning for you.

**Comment by galbramc** [comment]
ok, I'm going to be up for about another hour. If you merge this branch I can updated the counts. If you merge it later all pull requests will go red until I can update the counts in the morning (1 am or so your time).

**Comment by whoburg** [comment]
Thanks! Merging now -- we have no other open gpfit PR's, so hopefully the delay before count-resetting will not be an issue.

**Comment by galbramc** [comment]
You have a failing unit test on El-Cap:

https://acdl.mit.edu/csi/job/gpfit_Push/buildnode=macys_ElCap/19/

but it's an assertTrue instead of an assertGreater (or something like that), so I can't tell if it's a tolerance problem or a real error. The counts are reset on the push for all other machines, but I'm going to have to reset the counts again on El-Cap once you get this fixed.

**Comment by galbramc** [comment]
test this please

**Pull request merged**
