### PR TITLE
setup for CI

### PR DESCRIPTION
**Pull request by whoburg**
fixing `__init__.py` as suggested by @galbramc

### CODE REVIEW

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
the unit tests are currently failing

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
retest this please

**Comment by whoburg** [comment]
some of the failures this is likely encountering are addressed over at #31  -- shall I merge this into that?

**Comment by galbramc** [comment]
sure, do the merge

**Comment by whoburg** [comment]
yep -- the import error I'm seeing is already addressed in #31. I'll try to merge this into that so we have a single PR to deal with.

**Comment by whoburg** [comment]
ok, all commits in this PR are captured in #31  -- closing this.

**Comment by galbramc** [comment]
retest this please

**Pull request closed without merging**
